### ISSUE TITLE
Rename info.txt to addon.txt

### ISSUE THREAD

**Issue by redsigma** [whisperity/SharpGMad#11]
Add an option to rename the info.txt file that is generated to addon.txt so the addons are detected.

**Comment by redsigma** [comment]
Or better generate both of them :D

**Comment by whisperity** [comment]
Uh, why is this needed? Admittedly I have not touched GMod for a couple of years now. Is legacy addon structures still supported? Did Garry explicitly force their name to be different?

**Comment by redsigma** [comment]
From my experiments info.txt filename does no longer work but if you rename it to addon.txt it works. Also I'll leave this info here: extract addons should have the folder in lowercase else it won't be detected on linux.

**Comment by whisperity** [comment]
@redsigma I have implemented the fix for both lowercase output folder and the `addon.txt` writing. Please check if these work now. :blush: 
[SharpGMad_1.2-9-ge025f78.zip](https://github.com/whisperity/SharpGMad/files/2300417/SharpGMad_1.2-9-ge025f78.zip)

**Comment by redsigma** [comment]
Just checked with the above zip and it doesn't create any addons.txt
It does create the info.txt file only, if i check that checkbox in the extract window.

**Comment by whisperity** [comment]
Alright I see the problem now. It looks like the extraction logic on the command-line and in the clickable window is duplicated. (I thought I made sure the logic is only in one place but I guess I only wanted to do it, never actually got to do it.)

Try with this, please: I'm sure it should work now.
[SharpGMad_1.2-9-g129e317.zip](https://github.com/whisperity/SharpGMad/files/2321466/SharpGMad_1.2-9-g129e317.zip)

**Comment by redsigma** [comment]
Ok i can confirm that it works with both .exe files. The Create legacy info.txt file checkbox generates both the addon.txt and info.txt file.

The only problem is that the generated output folder is not in lowercase if the .gma filename contains uppercase characters.

Also another thing but it's not that important, would be to make the addon.txt file be extracted by default, without checking the info.txt checkbox.

**Comment by whisperity** [comment]
The foldername-filename matching and the non-generation of `addon.txt` is because these so called "legacy operations" are trying to perfectly mimic the official `gmad`'s behaviour.

**Comment by whisperity** [comment]
Implemented in 129e3178d8ce440c9d2a50cc5ef6dcaa0bc85f62.
