### ISSUE TITLE
Failed to create the addon

### ISSUE THREAD

**Issue by Solunae** [whisperity/SharpGMad#5]
An exception happend while compiling the addon.

Exception of type 'System.OutOfMemoryException' was thrown.

Tried converting a 200mb folder, guess the program can't handle it?

**Comment by whisperity** [comment]
Indeed, there was a problem for which I'd like to apologize. The program loaded and kept each and every file in the memory, which resulted in a quick overflow if there were too many big files. (Overflow happens somewhere around 1.2 GiB of RAM usage)

The behaviour is fixed (mainly in 66100087134d9d5de0e643c6fab1be90f03150b2) and now hard-drive backed storage is used for temporary files.

Just a test result:
- Using the master version 1.0.1, adding a ~1 gigabyte structure to a GMA (with tons of other, mainly `.svn` files not allowed by whitelist) resulted in lots of reading and memory usage until it went to boom at the limit.
- Current code no longer reads the files it cannot add to memory (this fixed the overuse of HDD) and files it can add are copied to your `Temp` folder until the addon is saved. Memory usage is around 40 MiB average unless there is a file being copied (then it goes up high), but I experienced no crashes with a **definitely** unlikely test case.
